default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jj_users_posts_development

test:
  <<: *default
  database: jj_users_posts_test
#  database: <%#= ENV.fetch('TEST_DATABASE') { 'jj_users_posts_test' } %>

#production:
#  <<: *default
#  database: jibber_jabber_users_posts_production
#  username: jibber_jabber_users_posts
#  password: <%#= ENV["JIBBER_JABBER_USERS_POSTS_DATABASE_PASSWORD"] %>
