name: CD

on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ main, dev ]
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t jibber-jabber-posts .
      - name: Tags
        run: |
          docker tag jibber-jabber-posts ${{ secrets.DOCKER_USER }}/jibber-jabber-posts:${{ github.sha }}
          docker tag jibber-jabber-posts ${{ secrets.DOCKER_USER }}/jibber-jabber-posts:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/jibber-jabber-posts:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/jibber-jabber-posts:latest