name: CD - Dev

on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ dev ]
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t jibber-jabber-posts-dev .

      - name: Tags
        run: |
          docker tag jibber-jabber-posts-dev ${{ secrets.DOCKER_USER }}/jibber-jabber-posts-dev:${{ github.sha }}
          docker tag jibber-jabber-posts-dev ${{ secrets.DOCKER_USER }}/jibber-jabber-posts-dev:latest

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/jibber-jabber-posts-dev:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/jibber-jabber-posts-dev:latest

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/dev.key
          chmod 600 ~/.ssh/dev.key
          cat >>~/.ssh/config <<END
          Host dev
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/dev.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_DEV_USER }}
          SSH_KEY: ${{ secrets.SSH_DEV_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_DEV_HOST }}

      - name: Stop the server
        run: ssh dev 'docker-compose stop'

      - name: Remove container and image
        run: ssh dev 'docker container rm posts && docker image rm georgesstefan/jibber-jabber-posts-dev'

      - name: Start the server
        if: ${{ always() }}
        run: ssh dev 'docker-compose up'