name: CD - Prod

on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ main ]
    types:
      - completed

jobs:
  cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04

#    services:
#      postgres:
#        image: postgres:10.8
#        env:
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: ""
#          POSTGRES_DB: jj_users_posts_development
#        ports:
#          - 5432:5432
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t jibber-jabber-posts-prod .
#        env:
#          POSTS_DB_HOST: postgres #${{ secrets.POSTS_DB_HOST }}
#          POSTS_DB_USER: postgres #${{ secrets.POSTS_DB_USER }}
#          POSTS_DB_PASSWORD: ""
#          PGHOST: postgres
#          PGUSER: postgres
#          PGPORT: ${{ job.services.postgres.ports[5432] }}

      - name: Tags
        run: |
          docker tag jibber-jabber-posts-prod ${{ secrets.DOCKER_USER }}/jibber-jabber-posts-prod:${{ github.sha }}
          docker tag jibber-jabber-posts-prod ${{ secrets.DOCKER_USER }}/jibber-jabber-posts-prod:latest

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/jibber-jabber-posts-prod:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/jibber-jabber-posts-prod:latest

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_PROD_USER }}
          SSH_KEY: ${{ secrets.SSH_PROD_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_PROD_HOST }}

      - name: Stop the server
        run: ssh prod 'docker-compose stop'

      - name: Remove container and image
        run: ssh prod 'docker container rm posts && docker image rm georgesstefan/jibber-jabber-posts-prod'

      - name: Pull new image
        run: ssh prod 'docker pull ${{ secrets.DOCKER_USER }}/jibber-jabber-posts-prod:${{ github.sha }}'

      - name: Start the server
        if: ${{ always() }}
        run: ssh prod 'docker-compose up -d > /dev/null 2>&1'