name: CD - Prod

on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ main ]
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t jibber-jabber-posts-prod .
      - name: Tags
        run: |
          docker tag jibber-jabber-posts-prod ${{ secrets.DOCKER_USER }}/jibber-jabber-posts-prod:${{ github.sha }}
          docker tag jibber-jabber-posts-prod ${{ secrets.DOCKER_USER }}/jibber-jabber-posts-prod:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/jibber-jabber-posts-prod:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/jibber-jabber-posts-prod:latest