name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-20.04
    container: ruby:3.0

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
        env:
          ImageOS: ubuntu20
      - name: Install dependencies
        run: bundle install
      - name: Run rspec tests
        run: bundle exec rspec
  cd:
    runs-on: ubuntu-20.04
    needs: ci

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t jibber-jabber-posts .
      - name: Tags
        run: |
          docker tag jibber-jabber-posts ${{ secrets.DOCKER_USER }}/jibber-jabber-posts:${{ github.sha }}
          docker tag jibber-jabber-posts ${{ secrets.DOCKER_USER }}/jibber-jabber-posts:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/jibber-jabber-posts:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/jibber-jabber-posts:latest