name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-20.04
    container:
      image: ruby:3.0.4

    services:
      postgres:
        image: postgres:12.9
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: bundle install

      - name: Install rspec
        run: rails generate rspec:install

      - name: Setup database
        env:
          PGHOST: postgres
          PGUSER: postgres
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          RAILS_ENV: test
        run: rails db:create

      - name: Run rspec tests
        run: rspec
  cd:
    runs-on: ubuntu-20.04
    needs: ci

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t jibber-jabber-posts .
      - name: Tags
        run: |
          docker tag jibber-jabber-posts ${{ secrets.DOCKER_USER }}/jibber-jabber-posts:${{ github.sha }}
          docker tag jibber-jabber-posts ${{ secrets.DOCKER_USER }}/jibber-jabber-posts:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/jibber-jabber-posts:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/jibber-jabber-posts:latest